#!/bin/sh

set -e


. /usr/share/debconf/confmodule

while true; do
    db_input medium android-sdk-installer/dldir || true
    db_go
    db_get android-sdk-installer/dldir
    if [ -n "$RET" ] && [ -d "$RET" ];then
        for file in $RET/*.zip;do
            case "$(basename "$file")" in
                tools*) tools=$file ;;
                android*) platform=$file ;;
                platform-tools*) platform_tools=$file ;;
                build-tools*) build_tools=$file ;;
            esac
        done
		echo tools: $tools
		echo platform: $platform
		echo platform-tools: $platform_tools
		echo build-tools: $build_tools
		if ( unzip -qqt "$tools" && unzip -qqt "$platform" && unzip -qqt "$platform_tools" && unzip -qqt "$build_tools" ) 2>&1 > /dev/null;then
            break
        fi
    elif [ -z "$RET" ];then
        break
    fi
    db_reset android-sdk-installer/baddldir || true
    db_reset android-sdk-installer/dldir || true
    db_input medium android-sdk-installer/baddldir || true
    db_go
done
