#!/bin/sh

set -e


. /usr/share/debconf/confmodule

while true; do
    db_input medium android-sdk-installer/dldir || true
    db_go
    db_get android-sdk-installer/dldir
    if ( [ -n "$RET" ] && [ -d "$RET" ] ) || $AUTOSET;then
        AUTOSET=false
		tools="$RET"/tools*.zip
		platform="$RET"/android*.zip
		platform_tools="$RET"/platform-tools*.zip
		build_tools="$RET"/build-tools*.zip
		echo tools: $tools
		echo platform: $platform
		echo platform-tools: $platform_tools
		echo build-tools: $build_tools
		if ( unzip -qqt "$tools" && unzip -qqt "$platform" && unzip -qqt "$platform_tools" && unzip -qqt "$build_tools" );then
            break
        fi
    elif [ -z "$RET" ];then
        break
    fi
    db_reset android-sdk-installer/baddldir || true
    db_reset android-sdk-installer/dldir || true
    db_input medium android-sdk-installer/baddldir || true
    db_go
done
