#!/bin/sh

#DEBHELPER#

# don't set -e before debhelper, because removal stuff like defoma may fail,
# but we're still successfully uninstalled.
set -e

if [ "$1" = "remove" ]; then
	rm -rf /opt/android-sdk
fi

exit 0
